### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by volodymyr-kushnir** [ArtyomMoiseenko/Lecture1_Git#1]
@ArtyomMoiseenko, привіт. Може додасиш **README.md** до проекту? Спочатку з коротким описом репозиторію, а потім і лінки на статті допишеш, ммм? Опціонально, звичайно, як захочеш, на твій вибір. Я просто подумав шо було б гарно додати тобі проблему в **Issues**, яку б ти закрив.
Крім того, з першого разу репозиторій не зайшов, я так бачу. Якщо є труднощі з чимось — звертайся @volodymyr-kushnir. Як воно взагалі, порядок?

**Comment by ArtyomMoiseenko** [comment]
@volodymyr-kushnir, здравствуйте. Всё вроде бы получилось, добавил README.md, спасибо за совет, только вопрос есть: нужно ли удалять дополнительные ветви? Так как на видео они были удалены, но можно ли будет увидеть, что я создавал для всех изменений новые ветви.

**Comment by volodymyr-kushnir** [comment]
![image](https://cloud.githubusercontent.com/assets/10290626/26283217/140ebeda-3e2c-11e7-9621-5cae57f60237.png)
@ArtyomMoiseenko, зараз я бачу тільки отак, можливо через те шо інші гілки в тебе локальні і ще не пушнуті в апстрім. Головне бачити повідомлення про **"Merge branch ... into master"**, тому їх наявність в списку branch-ів ні на що не впливає, можеш видаляти, а можеш і лишити.

**Comment by volodymyr-kushnir** [comment]
![image](https://cloud.githubusercontent.com/assets/10290626/26283248/e1658fee-3e2c-11e7-817b-a02a40b48940.png)
@ArtyomMoiseenko, для прикладу ось дерево мого **agenda**. Гілки вже видалені, проте чітко видно шо звідки куди впало.

**Comment by ArtyomMoiseenko** [comment]
@volodymyr-kushnir, я вроде бы всё "запушил". Такая ситуация возможна, еслия не комитил после слияния?

**Comment by volodymyr-kushnir** [comment]
@ArtyomMoiseenko, наразі виглядає шо в тебе всі комміти були в одну гілку. можливо ти гілки зробив, але не переключився на них і дальше коммітив в мастер? спробуй глянути `git reflog`, чи були там `merge`.

**Comment by ArtyomMoiseenko** [comment]
@volodymyr-kushnir, ![default](https://cloud.githubusercontent.com/assets/28815037/26283410/a3505686-3e30-11e7-9ea0-28778a7162ca.png)

**Comment by volodymyr-kushnir** [comment]
@ArtyomMoiseenko ах, тобто ти пушнув вже після того як змерджив те все докупи на локальній машині?

**Comment by ArtyomMoiseenko** [comment]
@volodymyr-kushnir, да. По-видимому, я сделал неверно. Мне заново тогда стоит переделать?

**Comment by volodymyr-kushnir** [comment]
@ArtyomMoiseenko да нє, забєй. так то це проблема формулювання завдання — я шось не спрогнозував такий розвиток подій і напевно буду просити в учасників академії ще `git reflog` в додачу.

Але якшо в тебе ше є час і бажання поклацати, то може заведи проект в **Projects** тут на **GitHub**'і, якісь може **Issues** зробиш собі. Словом, чекни мій репозиторій **agenda**, там є підказки. То опціонально, якшо захочеш поклацати.

**Comment by ArtyomMoiseenko** [comment]
@volodymyr-kushnir, спасибо за помощь. Я создал проект в Projects, а также Issues, где я указал проблему и скинул туда `git reflog`.
